const Constants = {
	RECEIVE_CURRENT_USER: "RECEIVE_CURRENT_USER",
	RECEIVE_ERRORS: "RECEIVE_ERRORS",
	RECEIVE_TWEETS: "RECEIVE_TWEETS",
	RECEIVE_NEW_TWEET: "RECEIVE_NEW_TWEET",
	RECEIVE_UPDATED_TWEET: "RECEIVE_UPDATED_TWEET",
	RESET_TWEETS: "RESET_TWEETS",
	FOLLOWING: "following",
	FOLLOWERS: "followers",
	LIKES: "likes",
	WITH_REPLIES: "with_replies",
	RESET_PROFILE_USER: "RESET_PROFILE_USER",
	RECEIVE_PROFILE_USER: "RECEIVE_PROFILE_USER",
	LIKES_FEED: "LIKES_FEED",
	CURR_USER_FEED: "CURR_USER_FEED",
	PROFILE_FEED: "PROFILE_FEED",
	NON_REPLY_PROFILE_FEED: "NON_REPLY_PROFILE_FEED",
	RECEIVE_USERS: "RECEIVE_USERS",
	RESET_USERS: "RESET_USERS",
	WRITING_TWEET: "WRITING_TWEET",
	NOT_WRITING_TWEET: "NOT_WRITING_TWEET",
	WRITING_REPLY: "WRITING_REPLY"
}

module.exports = Constants;